# Define the services and applications that make up your application.
services:
  backend-question_service:
    build: ./backend/question_service # Path to the directory containing the Dockerfile for building the question service image.
    ports:
      - 3001:3001 # Maps port 3001 on the host to port 3001 in the container, making the app accessible on the host.
    networks:
      - app-network 

  frontend:
    build: ./frontend
    ports:
      - 8080:80
    networks:
      - app-network

networks:
  app-network: # Defines a network named 'app-network'.
    driver: bridge # Uses the bridge driver for the network, which is the default and most common network type in Docker.
